# Generated by Django 4.1.3 on 2022-11-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palindrome',
            name='string',
            field=models.CharField(default='', max_length=6),
        ),
    ]
